# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoQ
                                 A QGIS plugin
 Automatización del procesamiento de cálculo de la escorrentía superficial con el método de Número de Curva 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-12-04
        copyright            : (C) 2024 by Fabio A. Montealegre M. & Fernanda J. Gaspari
        email                : fabio.montealegre@agro.unlp.edu.ar
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Fabio A. Montealegre M. & Fernanda J. Gaspari'
__date__ = '2024-12-04'
__copyright__ = '(C) 2024 by Fabio Alejandro Montealegre Medina - Fernanda Julia Gaspari / CEIDE-UNLP-CIC'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoQ class from file GeoQ.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geoq_V2 import GeoQPlugin
    return GeoQPlugin(iface)
