# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoQ
                                 A QGIS plugin
 Complemento para el modelado de escorrentía superficial
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-12-13
        copyright            : (C) 2021 by Fabio Alejandro Montealegre Medina - Fernanda Julia Gaspari / CEIDE-UNLP-CIC
        email                : fabio.montealegre@agro.unlp.edu.ar
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Fabio Alejandro Montealegre Medina - Fernanda Julia Gaspari / CEIDE-UNLP-CIC'
__date__ = '2021-12-13'
__copyright__ = '(C) 2021 by Fabio Alejandro Montealegre - Fernanda Julia Gaspari / CEIDE-UNLP-CIC'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoQ class from file GeoQ.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Geo_Q import GeoQPlugin
    return GeoQPlugin(iface)
